# Site settings
title: "Ella Lachman"
description: "Ella Lachman's personal website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ella O. Lachman"
#resume_title:                   "Nuclear Safety Inspector"
resume_contact_email:
  "ellal@berkeley.edu"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_about:	        true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "#about_bookmark"
  resume_website_url:           "#education_bookmark"
  resume_linkedin_url:          "#links_bookmark"
  resume_twitter_url:          "#skills_bookmark"
  resume_dribbble_url:         "#mentoring_bookmark"
  #resume_facebook_url:          "https://www.facebook.com/groups/ezlab/"
  
  #resume_instagram_url:         "gallery.html"
  

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
